### ISSUE TITLE
Track type summary?

### ISSUE THREAD

**Issue by alexpreynolds** [Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine#12]
Would it be possible to put together a summary of each of the track types offered? The manual explains deployment well, but it might be useful to have a section that shows each track type that is found in this engine, perhaps as compared with other genome browsers (elements, discrete or continuous signals, long-range interactions, stacked bar charts, etc.).

**Comment by caoxiaoyi03** [comment]
We have grouped all code referring to a single type of tracks together and are currently completing the documentation in JSDoc format. When it's done we will use `iron-component-page` to show them.

**Comment by caoxiaoyi03** [comment]
We have pushed a major update (#17 and #18 ) for the documentation. The description of track types are now accessible from [GIVE manual](https://github.com/Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine/tree/master/manuals).

JSDocs of all supported track types are intended for interested developers and will be further enriched in the future.
