### ISSUE TITLE
Custom reference genome default regions

### ISSUE THREAD

**Issue by azkalot1** [Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine#25]
Hi,

In my previous issue #7 it was mentioned
"We have applied a patch to the master fork. Now there should be no issue if the default chromosomal region falls outside of the reference. An error message will also show if any of the regions are invalid."

I am now using GIVE from docker (btw, thank you for that, it is super convenient!) and I tried to use my custom reference genome. I added it using Tutorials section. However, default regions were still "chr10:30000000-55000000" and "chr10:34900000-65000000"  (files html/components/basic-func/constants-template.js:20 and html/components/basic-func/constants.js:21) and I got an error "Invalid chromosome regions", so I had to change them to smth like chr1:1-100000 and only after that everything worked.

Since some people will probably use custom reference genomes, is it possible to fix this issue?

**Comment by caoxiaoyi03** [comment]
The base code has been updated to fix some errors when specifying default view windows via `defaultViewWindows` in `settings` column of `compbrowser`.`ref`. We will update documentation and GIVE-Toolbox accordingly to reflect this change.
