### ISSUE TITLE
Add Custom Track button grayed out

### ISSUE THREAD

**Issue by adelq** [Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine#36]
What are the conditions for adding a custom track? I cannot seem to be able to upload tracks, both from local files or from a URL, on the publicly accessible tracks and locally running instances.

![image](https://user-images.githubusercontent.com/929309/37056662-11bab728-2153-11e8-86cf-80146decfdbc.png)

**Comment by caoxiaoyi03** [comment]
This should be now closed by #91. We can reopen it if there is any problems.
