### ISSUE TITLE
About data format conversion

### ISSUE THREAD

**Issue by annlyuan** [Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine#41]
Since people usually have raw data in fasta.q format, .sam format or .bam format. It would be really nice if GIVE tutorials could mention some brief way for data format conversing. Such as by using Galaxy or any other tools to achieve the aim format. It doesn't have to be very detailed, a brief mention and provide us a link would be enough if it possible. Thank you!

**Comment by caoxiaoyi03** [comment]
Fastx format files needs to be mapped first to be used in GIVE browser. Here are some suggestions for sequence mappers if you don't have one in mind already or would like to explore.
-   For ChIP-Seq, ATAC-Seq, ChIA-PET, you may use [HISAT](http://ccb.jhu.edu/software/hisat2/index.shtml), [Bowtie](http://bowtie-bio.sourceforge.net/bowtie2/index.shtml), or [BWA](http://bio-bwa.sourceforge.net/).
-   For RNA-Seq (messenger, total, micro, *etc.*), you may use [HISAT](http://ccb.jhu.edu/software/hisat2/index.shtml), [STAR](https://github.com/alexdobin/STAR), or [Tophat](https://ccb.jhu.edu/software/tophat/index.shtml).
-   For Hi-C or other chromatin-structure-oriented sequencing, please refer to publications listed [here](https://www.ncbi.nlm.nih.gov/pubmed/?cmd=historysearch&querykey=1) or [HiCTool](https://doc.genomegitar.org/) for potential workflows.

For SAM/BAM files, we are currently working to implement support for indexed BAM files in GIVE. Meanwhile, you may refer to <http://seqanswers.com/forums/showthread.php?t=17297> for means of converting SAM/BAM files to bigWig format, which GIVE currently supports.

If you are using GALAXY, you may use `BEDTools` > `Genome Coverage` followed by `Convert Formats` > `Wig/BedGraph-to-bigWig` to convert BAM files to bigWig formats.

**Comment by annlyuan** [comment]
Thank you very much！
