### ISSUE TITLE
About how to deal with batch data

### ISSUE THREAD

**Issue by annlyuan** [Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine#42]
About how to deal with batch data.
I can visualize one sample by follow the tutorials and manuals, but what if I have more than one sample?

**Comment by caoxiaoyi03** [comment]
We have a set of tools named [`GIVE_ToolBox`](https://github.com/Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine/blob/master/manuals/3.1-GIVE-Toolbox-usages.md), including various scripts to add/change tracks/references. Because those are supposed to be invoked as one-liners, I think you might be able to incorporate those scripts into your own script with bash looping or something.

**Comment by annlyuan** [comment]
Thanks for your kind help!
 I managed to add batch data to build a new reference genome.
 But I met a another situation. Everything went well when I followed the example in tutorial 3.0 and also when I used only one sample of my data. Yet when I tried to apply the same protocol to the batch data, even if I just selected one of them for visualizing, the html could be browsed but the ‘waiting symbol’ never end... 
All my data are .bigwig format transformed from .bam, and the annotation files are downloaded from UCSC web. I have checked my data some times I didn't find any error in them. Is there any problem might be ignored by me？

**Comment by annlyuan** [comment]
<img width="1440" alt="screenshot 2018-03-21 19 06" src="https://user-images.githubusercontent.com/37343354/37993245-d745aa78-31c2-11e8-9a54-9d0d75b83e5b.png">

Here is a pic of the error in print page...

**Comment by annlyuan** [comment]
![screenshot 2018-03-27 13 31 07](https://user-images.githubusercontent.com/37343354/37993334-24d37892-31c3-11e8-8a4b-bbd27d35270c.png)
Here is a pic of print page that contained an error in it...

**Comment by annlyuan** [comment]
Problem solved !!!!! 
Turned out that I should be more careful in data pre-processing, especially when setting the path………………
thanks so much!

**Comment by caoxiaoyi03** [comment]
Although this issue has been closed, we'll improve error reporting mechanism in the next update so that it will be easier to pin down the problems.
