### ISSUE TITLE
Can't use initial_ref.sh successfully  to generate reference data

### ISSUE THREAD

**Issue by annlyuan** [Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine#66]
Hello, 
I'm trying to use the latest version of GIVE to visualize a new group of data from our lab, I used exactly the same pipeline and but failed to generate the reference data at the very beginning.( "bash initial_ref.sh -u root -p Admin2015 -r hg38 -s "Homo sapiens" -c human  -f /tmp/cytoBandIdeo.txt" ) 
Then I tried to follow the tutorial 3 step by step with the example data that GIVE-website offers for the customer, it surfed the same situation.
I tried to troubleshoot and find the construction in Mysql of reference didn't start at all. And then I changed my GIVE version to an earlier one, it can work smoothly again. I think something might be wrong at the new version, but I don't familiar with Mysql, so I decided to report this issue. 
Thank you for your kind help!

Best,
Yuan Liu

**Comment by frankyan** [comment]
Hi, I forgot to merge a pull which might be the reason. Can you update to the newest master branch of GIVE and try it again? Besides, the cytoBandIdeo.txt and other example files are now in /tmp/example_data dir as shown in the tutorial 3.
